#doing this podexample file after tainting a node with NoSchedule
# taint is used to reserve node for something. so that others won't use that node
#lable a node which u want pod to use that node
#kubectl label nodes <node-name> <key>=<value>

#case:1

#NoSchedule
#===========
# if you use NoSchedule, then u can't able to add new pod to that node but previous one will execute in same node
#kubectl taint nodes <node-name> <key>=<value>:NoSchedule
#EX:::  kubectl taint nodes ip-192-168-17-199.ec2.internal project=roboshop:NoSchedule


#-------------------------------------------------------------------------------------------------------

#case :2

#PreferNoSchedule
#================
# if you use PreferNoSchedule, then it try to not to schedule a new pod to that node but previous one will execute in same node
# it may assign pod to same node , it just try to not to schedule. not  condition , just a try.
#kubectl taint nodes <node-name> <key>=<value>:PreferNoSchedule
#EX:::  kubectl taint nodes ip-192-168-17-199.ec2.internal project=roboshop:PreferNoSchedule

#-------------------------------------------------------------------------------------------------------
#case : 3

# NoExecute
#================
# if you use NoExecute, then it don;t assign  new pod to that node and previous one will also exited from that node even it is running from long time
# no new one will attach and older also vanished
#kubectl taint nodes <node-name> <key>=<value>:NoExecute
#EX:::  kubectl taint nodes ip-192-168-17-199.ec2.internal project=roboshop:NoExecute
# NOTE--> here pod goes to PENDING STATE, because it don;t alow pod to get into node. so pod wont create and run , hence it is in PENDING STATE untill we delete it manually

#-------------------------------------------------------------------------------------------------------

# if we want to schedule pod even node is tainted we have to use TOLERATION concept
#TOLERATION:  A toleration doesn’t “force” scheduling; it just removes the restriction imposed by the taint.

apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  containers:
    - name: mongodb
      image: subbukola541/mongodb:1.0
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d  # select node which is in us-east-1d and assign pod to that node