# if we want to schedule pod even node is tainted we have to use TOLERATION concept
#TOLERATION:  A toleration doesn’t “force” scheduling; it just removes the restriction imposed by the taint.
# we have to match key values that used for taint. have to use same for pod file in toleration.
# so that it just removes the restriction imposed by the taint with those key values .

#example
#========
#kubectl taint nodes ip-192-168-17-199.ec2.internal project=roboshop:NoExecute // tainted

# NOTE: if you forgot to use TOLERATION and if node already tainted , pod will be in Scheduled state. keep this in mind
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "project"
      operator: "Equal"
      value: "roboshop"
      effect: "NoExecute"  # it matches node which tainted with "NoExecute" and executes pod inside that node
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1d

---
# NOTE: if you forgot to use TOLERATION and if node already tainted , pod will be in Scheduled state. keep this in mind
apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  containers:
    - name: mongodb 
      image: subbukola541/mongodb:1.0
  tolerations:
    - key: "project"
      operator: "Equal"
      value: "roboshop"
      effect: "NoExecute"  #  it matches node which tainted with "NoExecute" and executes pod inside that node

--- 
---
# NOTE: if you forgot to use TOLERATION and if node already tainted , pod will be in Scheduled state. keep this in mind
apiVersion: v1
kind: Pod
metadata:
  name: catalogue-pod
spec:
  containers:
    - name: mongodb 
      image: subbukola541/catalogue:1.0
  tolerations:
    - key: "project"
      operator: "Equal"
      value: "transport"    # kubectl taint nodes ip-192-168-42-86.ec2.internal project=transport:PreferNoSchedule
      effect: "PreferNoSchedule" #  it matches node which tainted with "PreferNoSchedule" and executes pod inside that node