# to label a node 
#kubectl label nodes <your-node-name> disktype=ssd


apiVersion: v1
kind: Pod
metadata:
  name: nginx-ssd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:  # it checks key and value i.e., label. If label matches it schedules pod in that node. or else pod is in PENDING state
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
  containers:
  - name: nginx
    image: nginx

---
 
apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:  # it checks key and value i.e., label. If label matches it schedules pod in that node. or else pod is goes to scheduler and it assigns to another node if any. if no node available and matched node has no resources. then also pod is in PENDING state
      - weight: 10 # it takes priority. if node matches pod creates in matches node. or else looks for another node
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1e # here in my case 1e zone, no node available
  containers:
  - name: mongodb 
    image: subbukola541/mongodb:1.0


---
 
apiVersion: v1
kind: Pod
metadata:
  name: catalogue-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:  # it checks key and value i.e., label. If label matches it schedules pod in that node. or else pod is goes to scheduler and it assigns to another node if any. if no node available and matched node has no resources. then also pod is in PENDING state
      - weight: 10 # it takes priority. if node matches pod creates in matches node. or else looks for another node
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c # here in my case 1e zone, no node available
  containers:
  - name: catalogue  
    image: subbukola541/catalogue:1.0