apiVersion: v1
kind: Pod
metadata:
  name: mongodb-with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: project 
            operator: In
            values:
            - roboshop 
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: mongodb
    image: subbukola541/mongodb:1.0
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: security
    #           operator: In
    #           values:
    #           - S2
    #       topologyKey: topology.kubernetes.io/zone
  
