apiVersion: v1
kind: pod
metadata: 
  name: pod-1
  labels:
    purpose: pod-affinity-practice

spec:
  containers:
    - name: ngonx
      image: nginx 


--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
  labels:
    project: roboshop
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose 
            operator: In
            values:
            - pod-affinity-practice
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: mongodb
    image: subbukola541/mongodb:1.0
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: security
    #           operator: In
    #           values:
    #           - S2
    #       topologyKey: topology.kubernetes.io/zone
  
