# Pod anti-Affinity is used to not to run pods in same node as our pod already running
# example if we have two pods  POD-1 and POD-2 and POD-1 is running in node-1
# if we don't want POD-2 to run on same node-1 that POD-1 running, use lables of POD-1 and use them in AntiPodAffinity section
#Like how nodeaffinity have hard and soft rule, same podAntiAffinity also have 

apiVersion: v1
kind: Pod
metadata: 
  name: pod-1
  labels:
    purpose: pod-anti-affinity-practice

spec:
  containers:
    - name: nginx
      image: nginx 


--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity-mongo
  labels:
    project: roboshop
spec:
  affinity:
    podAffinity:
      #HARD
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: purpose
                  operator: In
                  values:
                    - pod-anti-affinity-practice
            topologyKey: topology.kubernetes.io/zone
  containers:
  - name: mongodb
    image: subbukola541/mongodb:1.0

--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity-catalogue
  labels:
    project: roboshop
spec:
  affinity:
    podAffinity:
      #HARD
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: purpose
                  operator: In
                  values:
                    - pod-anti-affinity-practice
            topologyKey: topology.kubernetes.io/zone
  containers:
  - name: catalogue
    image: subbukola541/catalogue:1.0
